
train_test_split:
  test_size: 0.3 # do not change value
  random_state: 20

feature_selection:
  LinearSVC:
    C: 0.01
    penalty: l1
    dual: False

model:
  type: "LogisticRegression"
  params:
    random_state: 420